language: rust
rust: nightly
cache: cargo

services:
  - postgresql

before_install:
  - pqsl -U postgres -f init.sql

before_script: 
  - cargo run & sleep 60
  - curl 'http://localhost:8000/api/tags'

script: cargo test -- --test-threads=1
